spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/db?authSource=admin&retryWrites=true&maxIdleTimeMS=60000&socketKeepAlive=true
  shell:
    interactive:
      enabled: true
